version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1-2017-03
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./TestUtils.sln && dotnet publish ./TestUtils.sln -c Release -o ./obj/Docker/publish"
